alias ls="exa --all --icons --grid"
alias zshconfig="nvim ~/.zshrc"
alias cat="bat"
alias zshalias="nvim ~/.oh-my-zsh/custom/my-aliases.zsh"
alias vi="nvim"
alias vim="nvim"
alias sshdesktop="ssh garrettg@192.168.250.89 -p 22"
