alias ls="exa --all --icons --group-directories-first"
alias zshconfig="nvim ~/.zshrc"
alias cat="bat"
alias zshalias="nvim ~/.oh-my-zsh/custom/my-aliases.zsh"
alias vi="nvim"
alias vim="nvim"
alias nvimconfig="nvim ~/.config/nvim"
